# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2023-08-20 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20180219_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='price',
            field=models.CharField(max_length=3),
        ),
    ]
