# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2023-08-20 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20230820_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
